[unix_http_server]
file=/run/signal-bridge-supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/dev/fd/1
logfile_maxbytes=0
pidfile=/run/signal-bridge-supervisord.pid
childlogdir=/tmp
strip_ansi=true

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/signal-bridge-supervisor.sock

[include]
files=/etc/supervisor/conf.d/*.conf
